#!/usr/bin/env bash

# PLEASE NOTE: This script has been automatically generated by conda-smithy. Any changes here
# will be lost next time ``conda smithy rerender`` is run. If you would like to make permanent
# changes to this script, consider a proposal to conda-smithy so that other feedstocks can also
# benefit from the improvement.

FEEDSTOCK_ROOT=$(cd "$(dirname "$0")/.."; pwd;)
RECIPE_ROOT=$FEEDSTOCK_ROOT/recipe

docker info

config=$(cat <<CONDARC

channels:
 - conda-forge
 - defaults # As we need conda-build

conda-build:
 root-dir: /feedstock_root/build_artefacts

show_channel_urls: true

CONDARC
)

mercurial_config=$(cat <<MEOF
[mercurial.selenic.com]
name=mercurial.selenic.com
baseurl=https://www.mercurial-scm.org/release/centos6
enabled=1
# Temporary until we get a serious signing scheme in place,
# check https://www.mercurial-scm.org/wiki/Download again
gpgcheck=0
MEOF
)

cat << EOF | docker run -i \
                        -v ${RECIPE_ROOT}:/recipe_root \
                        -v ${FEEDSTOCK_ROOT}:/feedstock_root \
                        -a stdin -a stdout -a stderr \
                        condaforge/linux-anvil \
                        bash || exit $?

export BINSTAR_TOKEN=${BINSTAR_TOKEN}
export PYTHONUNBUFFERED=1

echo "$config" > ~/.condarc
echo "$mercurial_config" > /etc/yum.repos.d/mercurial.selenic.com.repo
yum install -y mercurial
# A lock sometimes occurs with incomplete builds. The lock file is stored in build_artefacts.
conda clean --lock

conda config --set anaconda_upload yes
anaconda config --set token ${BINSTAR_TOKEN}
anaconda login --username ${BINSTAR_USER} --password ${BINSTAR_PASS}
conda install --yes --quiet conda-forge-build-setup
source run_conda_forge_build_setup

# Embarking on 6 case(s).
    set -x
    export CONDA_NPY=110
    export CONDA_PY=27
    set +x
    conda build /recipe_root --quiet || exit 1
    # upload_or_check_non_existence /recipe_root xarthisius --channel=main || exit 1

    set -x
    export CONDA_NPY=111
    export CONDA_PY=27
    set +x
    conda build /recipe_root --quiet || exit 1
    # upload_or_check_non_existence /recipe_root xarthisius --channel=main || exit 1

    set -x
    export CONDA_NPY=110
    export CONDA_PY=35
    set +x
    conda build /recipe_root --quiet || exit 1
    # upload_or_check_non_existence /recipe_root xarthisius --channel=main || exit 1

    set -x
    export CONDA_NPY=111
    export CONDA_PY=35
    set +x
    conda build /recipe_root --quiet || exit 1
    # upload_or_check_non_existence /recipe_root xarthisius --channel=main || exit 1

    set -x
    export CONDA_NPY=110
    export CONDA_PY=36
    set +x
    conda build /recipe_root --quiet || exit 1
    # upload_or_check_non_existence /recipe_root xarthisius --channel=main || exit 1

    set -x
    export CONDA_NPY=111
    export CONDA_PY=36
    set +x
    conda build /recipe_root --quiet || exit 1
    # upload_or_check_non_existence /recipe_root xarthisius --channel=main || exit 1
EOF
